roles:
  - name: common
    src: escalate.common

  - name: cron
    src: escalate.cron

  - name: docker
    src: escalate.docker

collections:
  - name: community.docker

  - name: community.general
